file =open("example.txt","w")
file.write("hello,how are you!")
file.write("welcome to file handeling method in python ")
file.close()
print("file opened sucessfully")
file=open("example.txt","r")
content=file.read()
print("File Content:\n", content)
file.close()
file=open("example.txt","a")
file.write("\n welcome to hightech city hydrabad")
file.close()